### ISSUE TITLE
iOS: no cancel/close/back button on Ver-ID-Credentials screen

### ISSUE THREAD

**Issue by sanidkpc** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#17]
Hi @jakubdolejs,
If we show the session guide `settings.showGuide = true;` and when the Ver-ID-Credentials screen displayed, we are unable to close/cancel that screen and go back to our main app. 

If a user open Ver-ID-Credentials from our inapp with showGuide flag on, there is no way to go back in our main app unless he/she process a Card Capture.

**Please observer the screenshot below**

![simulator screen shot - iphone 6s - 2019-02-14 at 19 31 12](https://user-images.githubusercontent.com/6288562/52789840-39d18600-308f-11e9-8076-d97d8e6ba29c.png)
No back/cancel button available in this screen, we are unable to go back in our main app.

On **Android** we can go back to our main app by pressing hardware back button, but in iOS we have no option.

I would greatly appreciate your feedback on this.
Thank you

**Comment by jakubdolejs** [comment]
Fixed in https://github.com/AppliedRecognition/Ver-ID-Credentials-Apple/commit/1cd1c74e93606e835e3279e6afdc084e3e34d0e0. Please update the VerIDCredentials framework from CocoaPods to version 2.1.11.
