### ISSUE TITLE
iOS: No guid corners when reading back of the ID card [barcode feature]

### ISSUE THREAD

**Issue by sanitul** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#18]
Hi @jakubdolejs,
For `Scan Front` of a ID Card, we have a **card's corner guideline** in the camera surface but when we are going to read `back of the ID Card` there is no corner guideline. So we can not adjust the camera with the card surface.

**Please observer the screenshot below**

![img_0648](https://user-images.githubusercontent.com/47731403/53021939-78e34b00-3484-11e9-814e-082ccdfcdfaf.PNG)

**Please note:** For android platform this feature available. we do have the card's corner guideline [back of ID Card] for Android but this feature is missing on iOS.

I would greatly appreciate your feedback on this.
Thank you

**Comment by jakubdolejs** [comment]
Hi @sanitul, the two platforms use different technology to read barcodes. The corner animation is not available on iOS. I added a feature request in the Credentials framework for iOS but at the moment it's not on our roadmap to add it. I will update this ticket when/if we add it to the product roadmap.
