### ISSUE TITLE
Credentials plugin contains person plugin

### ISSUE THREAD

**Issue by andreyliventsev** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#2]
Please add to the docs information about plugin content. This Ver-ID-Credentials-Cordova-Plugin already contains Ver-ID-Person-Cordova-Plugin features. 
User not allowed to install both of them.

**Comment by jakubdolejs** [comment]
Added instruction in [README](https://github.com/AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin/blob/master/README.md). Thank you @andreyliventsev for pointing this out.
