### ISSUE TITLE
Ver-ID-Credentials screen, Cancel button configurable

### ISSUE THREAD

**Issue by sanitul** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#21]
Hi @jakubdolejs,

When the Ver-ID-Credentials screen displayed, we can close/cancel that screen and go back to our main app.

But is there any way we can make this **Cancel button configurable**, whether this cancel button should show or not.

`settings.showCancelButton = true/false`

So if a user open Ver-ID-Credentials, he/she must process a Card Capture, if showCancelButton set false.

![Simulator Screen Shot - iPhone 6 - 2019-03-27 at 19 57 57](https://user-images.githubusercontent.com/47731403/55083670-1a863980-50ce-11e9-92d2-a6c225a86e9a.png)
I would greatly appreciate your feedback on this.
Thank you

**Comment by sanitul** [comment]
Hi @jakubdolejs,
Any update on this issue.
I would greatly appreciate your feedback on this.
Thank you

**Comment by jakubdolejs** [comment]
Hello @sanitul, apologies for the delay. We will shortly be releasing a new version of the iOS SDK that will allow more control of how the view controllers are presented. I'll update this issue once it's available. Thank you for your patience.

**Comment by sanitul** [comment]
Hi @jakubdolejs,
Thanks for the update.
Have a question about another issue:
Issue title: **iOS: Ver-ID-Credentials capture ID response imagePath, cardImage not found**
Issue link: https://github.com/AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin/issues/22
is this issue removed? what is the status of this issue.
Thank you

**Comment by jakubdolejs** [comment]
Hi @sanitul, I transferred the issue to the Credentials SDK. That's where the result object serialisation is defined. We'll be releasing an update next week that addresses the issue.
