### ISSUE TITLE
AR not loading on iOS

### ISSUE THREAD

**Issue by haydursek** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#23]
We are having an issue loading AR and getting the following error.

`AR err: The opration couldn't be completed. (VerID.ResourceLoader.ResourceLoaderError error 5.)`

**Comment by jakubdolejs** [comment]
Hello @haydursek,
Please verify that:

1. [VerIDModels](https://github.com/AppliedRecognition/Ver-ID-Models.git) is being copied into your application's resources.
2. The **VerIDModels** directory files are checked out using [Git LFS](https://git-lfs.github.com).
3. The **VerIDModels** directory contains the following files and their sizes match the values in brackets:

    - dlib_face_recognition_resnet_model_v1.dat (9.38 MB)
    - fhogcascade_face_frontal.dat (151 KB)
    - haarcascade_mcs_lefteye.xml (759 KB)
    - haarcascade_mcs_righteye.xml (1.32 MB)
    - haarcascade_smile.xml (267 KB)
    - mmod_human_face_detector.dat (713 KB)
    - shape_predictor_68_face_landmarks.dat (10.5 MB)
