### ISSUE TITLE
Android[branch: swift4.2]: Driving license backside barcode reading process never finished

### ISSUE THREAD

**Issue by sanitul** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#24]
Hi @jakubdolejs,
I pull the plugin `Ver-ID-Credentials-Cordova-Plugin` from the latest branch **swift4.2**. In this branch iOS card image retrieve issue resolve.

But we got another problem on Android. At the time of capturing back of the ID card barcode, Barcode reading process never finish. It never return the data or anythings, rather than the camera continue focusing [with guid corners] at barcode area.

**Screenshot below:**

![Screenshot_20190508-165105](https://user-images.githubusercontent.com/47731403/57370377-d6e51c00-71b1-11e9-97d0-4540445ee6f5.png)

**Android Logcat:**
```
05-08 16:54:43.787 10480-13872/com.qa.E/libc: Access denied finding property "vendor.camera.aux.packagelist"
05-08 16:54:43.858 10480-10490/com.qa.W/System: A resource failed to call close. 
05-08 16:54:43.906 10480-13872/com.qa.W/IlIlllllII.java:2446@Camera1: Preview is already active
05-08 16:55:06.794 10480-10490/com.qa.W/System: A resource failed to call destroy. 
```
**Ionic cordova info:**
```
Ionic:

   ionic (Ionic CLI)  : 4.8.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/bs228/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.15.1 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```
I would greatly appreciate your feedback on this.
Thank you

**Comment by jakubdolejs** [comment]
Hi @sanitul, we just tested this on a couple of Android devices and it seems to be working fine. Do you mind trying it with a real licence instead of scanning an image on screen? It's likely that the barcode is found but it can't be decoded because of the artifacts created by the monitor.

**Comment by sanitul** [comment]
Yes this is the problem cause by monitor artifacts.
we can close this issue.
