### ISSUE TITLE
No Cancel or Close Button on Android

### ISSUE THREAD

**Issue by ahsanhabib23** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#25]
On **IOS**, we have a **CANCEL** button which triggers an event. But on **Android**, there is no **CANCEL** button. However, we can use the hardware back button to navigate back. Upon clicking the Hardware back button, the AR screen closes but it does not trigger any event or error which can be caught.

![rsz_screenshot_20190509-165438](https://user-images.githubusercontent.com/47731442/57449161-1298e800-727d-11e9-8130-6fd4a94f1bcd.png)

**Ionic cordova info:**
```
Ionic:

   ionic (Ionic CLI)  : 4.8.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/bs228/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.15.1 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```

I would greatly appreciate any feedback on this.
Thank you

**Comment by jakubdolejs** [comment]
Hello @ahsanhabib23, we will match the iOS behaviour with the hardware back button functioning the same as the iOS Cancel button.
