### ISSUE TITLE
Android [branch: swift4.2]: How do I retrieve face image? 

### ISSUE THREAD

**Issue by sanitul** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#27]
Is there any away to retrieve the face image after a successful card and face scan?
at ver-id document response we got.
```json
"faces": [
	{
		"bounds": {
			"x": 130.0,
			"y": 441.0,
			"width": 684.0,
			"height": 856.0
		}, // The bounds of the face in the image in pixels,
		"faceTemplate": {
			"data": "base64-encoded-data",
			"version": 1
		} // Template used for face comparison (see below)
	}
],
```
Here I'm getting faceTemplate data but not imageUri or base64 image data.

Further inspect I see all the faceimages and card [front] images are save in device
`file:///data/user/0/com.xx.xxx/cache/image_3873477644791190950.jpg` location.

From that directory I can't distinguish which images are for faces or card because all the image are save in same location with arbitrary name.

**info:** for iOS, face and card image was saved in different location

**Comment by jakubdolejs** [comment]
Hi @sanitul, the image is encoded using [data URI scheme](https://en.wikipedia.org/wiki/Data_URI_scheme) and it's part of the page object.
```
{"document":{"pages":[{"image":"data:image/jpeg;base64,imagedata"}]}}
```

**Comment by sanitul** [comment]
I understand, But that image is for Card Front Image not the face image. 
I want to retrieve the selfie live face detection image.

Android ver-id document response are given below.

<img width="712" alt="Screen Shot 2019-05-15 at 4 50 37 PM" src="https://user-images.githubusercontent.com/47731403/57770366-f4763080-7731-11e9-833a-c5b3386ca253.png">

**Comment by jakubdolejs** [comment]
You'll decode the `image` and crop it to the bounds found in the `faces` array. You can create a canvas element and draw the image onto it. Here is a complete example:
```javascript
var document; // Document received in the ID capture session result
var canvas = document.createElement("canvas");
var context = canvas.getContext("2d");
var image = new Image();
image.onload = function() {
    var crop = document.pages[0].faces[0].bounds;
    canvas.width = crop.width;
    canvas.height = crop.height;
    context.drawImage(image, 0-crop.x, 0-crop.y);
    var faceImage = canvas.toDataURL("image/jpeg", 0.95);
}
image.src = document.pages[0].image;
```

**Comment by sanitul** [comment]
Hi @jakubdolejs,
Thanks for the solution, now I can retrieve face image from ID Card image using faces bounds.
But is there any way we can actually get the user **Live face (selfie)** from `verid.captureLiveFace(settings)` response?

**Comment by jakubdolejs** [comment]
Hi @sanitul,
Similar process:
```javascript
verid.captureLiveFace(settings).then(result => {
    var entry = result.getFaceImages(verid.Bearing.STRAIGHT)[0];
    var canvas = document.createElement(canvas);
    var context = canvas.getContext("2d");
    var image = new Image();
    image.onload = function() {
        var crop = entry.face;
        canvas.width = crop.width;
        canvas.height = crop.height;
        context.drawImage(image, 0-crop.x, 0-crop.y);
        var faceImage = canvas.toDataURL("image/jpeg", 0.95); // This is the image (as data URL) of the cropped face
    }
    image.src = entry.image;
})
```
