### ISSUE TITLE
Ver-ID-Credentials[branch: swift4.2]: How do we get ID Card Back image?

### ISSUE THREAD

**Issue by sanitul** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#28]
After a successfully scan we get document response with scanned Card Image. From here we are getting only Card Front Image as imagePath or imageUri. But what about the ID card back image [barcode feature]?
How do we get the ID Card Back image?

I would greatly appreciate your feedback on this.
Thank you

**Comment by jakubdolejs** [comment]
Hi @sanitul, we do not collect the back image, only the barcode.
