### ISSUE TITLE
Unable to install ‘Ver-ID-Credentials-Cordova-Plugin’ for ionic Cordova platform iOS

### ISSUE THREAD

**Issue by sanidkpc** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#4]
Before installing the plugin I set the Cordova iOS deployment target to 11,
so my podfile platform :ios, '11.0'
`<preference name="deployment-target" value="11.0" />` in config.xml
But after cloning the plugin repo to a local directory, I ran
`cordova plugin add <path to the plugin>`
but I am getting the error below:
```
Failed to install 'com-appliedrec-plugins-veridcredentials': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/bs228/Desktop/ionicdev/ionic/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```
after further inspect i notice when i add plugin its failed and changed the podfile platform to 8.0 as bellow
```
platform :ios, '8.0'
target 'demo' do
	project 'demo.xcodeproj'
	pod 'Ver-ID-Credentials', '~> 2.1'
end 
```
so I manually changes the podfile ios platform to 11.0 and add `use_frameworks!` too
```
platform :ios, '11.0'
target 'demo' do
	use_frameworks!
	project 'demo.xcodeproj'
	pod 'Ver-ID-Credentials', '~> 2.1'
end
```
then i run `pod install` from platforms/ios and successfully install the ‘com-appliedrec-plugins-veridcredentials’ plugin and dependencies.
```
Installing Ver-ID (3.5.3)
Installing Ver-ID-Credentials (2.1.9)
```
`ionic cordova build ios` build project successfully.  
open the cordova project .xcworkspace file in xcode and changes the build settings according to Ver-ID-Credentials-Cordova-Plugin documentation and set Swift Language Version to 4.2.
But the build failed and getting the error below
**Swift compiler error (33 count)**
in file platforms/ios/demo/Plugins/com-appliedrec-plugins-veridcredentials/VerIDPlugin.swift
screenshot shown below.

![51735203-ef24a580-20b0-11e9-92b7-e28ac2bac482](https://user-images.githubusercontent.com/6288562/51737134-116cf200-20b6-11e9-9e1b-43e1b9412f22.png)

================================

Cordova project platform: ionic

```
ionic info
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4, ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

Environment:

   ANDROID_HOME : /Users/bs228/Library/Android/sdk
```
@jakubdolejs,
I would greatly appreciate it if you kindly give me some feedback on this
Thank you

**Comment by jakubdolejs** [comment]
Hello @sanidkpc,

We published a few hooks that should resolve this issue.

1. Copy the files from [here](https://github.com/AppliedRecognition/Ver-ID-Person-Cordova-Plugin/tree/master/hooks) to your Cordova project's directory. I created a folder called "scripts" in my project when I tested it.
2. In your **config.xml** add these 3 lines within the `<platform name="ios"></platform>` tags:
    
    ```xml
    <hook src="scripts/podfilesetup.js" type="before_build" />
    <hook src="scripts/platformversion.js" type="before_build" />
    <hook src="scripts/swiftversion.js" type="before_build" />
    ```
3. Install the plugin. You'll see the `pod command failed` error but you can ignore it.
4. Run `cordova build`. The scripts will set the Swift version, platform version and update the Podfile before building the project.
