### ISSUE TITLE
iOS: plugin swift code compile error

### ISSUE THREAD

**Issue by sanidkpc** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#6]
After adding the cordova hooks for iOS.
as mentioned
```xml
<hook src="scripts/podfilesetup.js" type="before_build" />
<hook src="scripts/platformversion.js" type="before_build" />
<hook src="scripts/swiftversion.js" type="before_build" />
```
podfilesetup, platformversion and swiftversion all are perfectly setup the version accordingly before build. Now I can build the cordova project successfully.
But when I open the cordova app's iOS work space in Xcode and run for simulator/device **Build Failed**.
It can not compile 
`platforms/ios/demoapp/Plugins/com-appliedrec-plugins-veridcredentials/VerIDCredentialsPlugin.swift`
and 
`platforms/ios/demoapp/Plugins/com-appliedrec-plugins-veridcredentials/VerIDPlugin.swift`
screenshot shown below.
![51735203-ef24a580-20b0-11e9-92b7-e28ac2bac482](https://user-images.githubusercontent.com/6288562/52043628-67381300-256a-11e9-9df0-e5267ba00e6c.png)

It seems like swift code does not recognize `cordova CDVPlugin objects`. `Use of undeclared type 'CDVPlugin'`

After further research I find out cordova plugin written in swift need to add `bridging-header.h` which contains `#import <Cordova/CDV.h>`  and mention bridging path in `Build Settings->Objective-C Bridging Header`
maybe we need to add another hook for Creating a Bridging Header and mention the path in Build Settings->Objective-C Bridging Header. 

Reference URL: Creating a Bridging Header
https://stackoverflow.com/questions/25448976/how-to-write-cordova-plugin-in-swift
https://moduscreate.com/blog/writing-a-cordova-plugin-in-swift-for-ios/

================================

Cordova project platform: ionic

```
ionic info
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4, ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

Environment:

   ANDROID_HOME : /Users/bs228/Library/Android/sdk
```
@jakubdolejs ,
I would greatly appreciate it if you kindly give me feedback on this.
Thank you

**Comment by jakubdolejs** [comment]
Can you confirm that the code compiles and runs after adding the bridging header? We'll consider adding a hook for this but it seems like it's a change that should be made by the application and not by the plugin.

**Comment by sanidkpc** [comment]
Hi @jakubdolejs ,
as I inspect cordova ios platform already created bridging header file in 
`platforms/ios/demoapp/Bridging-Header.h`
but if we want to compile swift we need to manually refer this header file in `Build Settings->Objective-C Bridging Header`.
And yes if I mention the bridge  file location then I can compile the plugin swift code.
It will be much better if you create a hook for this.

Thank you.

**Comment by sanidkpc** [comment]
Hi @jakubdolejs,
you are right 'SWIFT_OBJC_BRIDGING_HEADER' should be set by the cordova application but somehow another plugin interrupt this header setting, That's why BRIDGING_HEADER not setting and swift code not compile.
I updated that existing plugin now 
`SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h`
set properly.
No need to write extra hook for this.
Thank you
I'm closing this issues.
