### ISSUE TITLE
iOS runtime error: Library not loaded

### ISSUE THREAD

**Issue by sanidkpc** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#7]
Hi @jakubdolejs ,
Reference from previos issues #6 . After manually add `bridging-header.h` and mention bridging path in `Build Settings->Objective-C Bridging Header`.
I can successfully compile plugins '`VerIDCredentialsPlugin.swift`'  and '`VerIDPlugin.swift`'. It can now access the cordova objects.
But I'm facing a runtime error 
```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/bs228/Library/Developer/CoreSimulator/Devices/3E1F6184-A34D-4EE5-8336-959A158E7B2F/data/Containers/Bundle/Application/93CF408D-A4F0-4B95-A526-08CD703F8B65/demoapp.app/Frameworks/VerID.framework/VerID
  Reason: Incompatible library version: VerID requires version 1.0.0 or later, but libswiftAVFoundation.dylib provides version 0.0.0
```
================================

Cordova project platform: ionic

```
ionic info
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4, ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

Environment:

   ANDROID_HOME : /Users/bs228/Library/Android/sdk
```
I would greatly appreciate it if you kindly give me feedback on this.
Thank you

**Comment by jakubdolejs** [comment]
I believe this is related to Swift version. They can't be mixed in one project. Is it possible that the Swift version is not set to 4.2? Or that some other dependencies use a different Swift version?
Is this on a physical device or in an emulator?

**Comment by sanidkpc** [comment]
Hi @jakubdolejs ,
Thanks for the feedback.
after using the hooks for iOS, swift language version is set to 4.2 for the project target. I can confirm the changes in xcode 10. And also ios deployment target is set to iOS 11.0.
I'm not sure about the swift version of other dependencies library.
I'm running on physical device and simulator, both throw runtime error.
simulator: iPhone 6S v12.1
physical device: iPhone 7 plus v11.4
Thank you.

**Comment by sanidkpc** [comment]
Hi @jakubdolejs ,
after further inspect, I find out the cause of the error was the xcode 10 toolchains swift version selection. 
there is a swift version conflict in Toolchains. I remove other version and select 4.2.
Now the runtime issues resolved.
Thank you
I'm closing this issues.
